### ISSUE TITLE
Compatibility with dev Nette 3.0

### ISSUE THREAD

**Issue by Lumeriol** [aleswita/FormRenderer#1]
Declaration of AlesWita\FormRenderer\BootstrapV4Renderer::renderErrors(?Nette\Forms\IControl $control = NULL, $own = true) must be compatible with Nette\Forms\Rendering\DefaultFormRenderer::renderErrors(?Nette\Forms\IControl $control = NULL, bool $own = true): string

There will be more problems with incompatibility because now it is designed for Nette 2.4.

**Comment by aleswita** [comment]
Tnx for report. I will fix on Monday. Currently Im on holliday.

**Comment by aleswita** [comment]
Can you try dev-master version?

**Comment by Lumeriol** [comment]
Almost done, except missing return type - ": string". After adding it, it should be with fully functional.

And in addition, maybe should be better to use Nette libraries with "use" keyword than write them duplicitously in code?

**Comment by aleswita** [comment]
Tnx, return type now in dev-master too

**Comment by aleswita** [comment]
Now is valid the packages settings for install via composer.
