### ISSUE TITLE
setOption instead of addOption

### ISSUE THREAD

**Issue by cafesk8** [aleswita/FormRenderer#3]
Hello,
in Nette 2.4 i get an error when trying. 

`$form->addText('text1', 'Label:')->addOption('left-addon', 'addon text');`

I need to use setOption instead.

`$form->addText('text1', 'Label:')->setOption('left-addon', 'addon text');`

Please fix this in your documentation if you think there isn't problem on my side.

**Comment by aleswita** [comment]
Hi, its typo in docs... tnx for report it.
