### ISSUE TITLE
Datetime do formuláře

### ISSUE THREAD

**Issue by alena424** [aleswita/FormRenderer#4]
Ahoj, chci se zeptat/poprosit o rozšíření/poradit, jak pomocí tohoto formuláře můžu přidat input pro Datetime?

Ještě by mě zajímalo, jestli by nešlo nějak udělat, abych do right-addon mohla vložit nějakou ikonu? Podle mě tam nyní lze vložit pouze text.

Díky za radu.

Alča

**Comment by aleswita** [comment]
Musis pro control nastavit html type, ktery podporuje primo Nette\Forms

```php
$form->addText('date', 'Date')
    ->setHtmlType('date');
```

A pokud chces do addonu vlozt ikonku, mozna bude fungovat tohle to
```php
$form->addText('date', 'Date')
    ->setOption('right-addon', Nette\Utils\Html::el('i')->setClass('icon class'));
```

**Comment by alena424** [comment]
Ano, takto jsem to měla (s tím setHtmlType), ale šlo by to udělat:

1. aby mi to vracelo Datetime a ne string, používám Doctrine 2 a v momentě, co chci uložit hodnotu data, dostávám chybu: Could not convert PHP value '2019-02-03' of type 'string' to type 'date'.
anebo
2. abych mohla použít nějaký Datetime picker buď https://github.com/radekdostal/Nette-DateTimePicker/tree/master/examples nebo datetimepicker přímo pro bootstrap https://eonasdan.github.io/bootstrap-datetimepicker/ 

Děkuji

Ta ikona už mi přidat jde, to je super 👍

**Comment by aleswita** [comment]
Pouzij na prvek addFilter

```php
$form->addText('date')
    ->addFilter(function ($value) {return new Nette\Utils\DateTime($value);});
